spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/sportsstore
        username: postgres
        password: 123
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    sql:
        init:
            mode: always
            