spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/sportsstore
        username: postgres
        password: 123
    jpa:
        hibernate:
            format_sql: true
            ddl-auto: update
        show-sql: true