spring:
    datasource:
        url: jdbc:postgresql://pg-15ec5d05-nikita-6d6f.f.aivencloud.com:15336/defaultdb?ssl=require&user=avnadmin&password=AVNS_tDJbvB9RGbMQgu-O4q8
    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
